-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-16 13:23:41 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE administrator (
    administratorkey SMALLINT NOT NULL,
    name             VARCHAR2(50 CHAR) NOT NULL,
    phonenumber      VARCHAR2(11 CHAR) NOT NULL
);

ALTER TABLE administrator ADD CONSTRAINT administrator_pk PRIMARY KEY ( administratorkey );

ALTER TABLE administrator ADD CONSTRAINT administrator_name_un UNIQUE ( name );

ALTER TABLE administrator ADD CONSTRAINT administrator_phonenumber_un UNIQUE ( phonenumber );

CREATE TABLE answer (
    answerkey     INTEGER NOT NULL,
    body          VARCHAR2(250 CHAR) NOT NULL,
    questionkey   INTEGER,
    salespointkey INTEGER,
    employeekey   INTEGER NOT NULL
);

ALTER TABLE answer ADD CONSTRAINT answer_pk PRIMARY KEY ( answerkey );

CREATE TABLE city (
    citykey    INTEGER NOT NULL,
    name       VARCHAR2(50 CHAR) NOT NULL,
    postalcode VARCHAR2(50 CHAR) NOT NULL,
    countrykey SMALLINT NOT NULL
);

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( citykey );

ALTER TABLE city ADD CONSTRAINT city_postalcode_un UNIQUE ( postalcode );

CREATE TABLE country (
    countrykey        SMALLINT NOT NULL,
    name              VARCHAR2(50 CHAR) NOT NULL,
    code              VARCHAR2(50 CHAR) NOT NULL,
    salesterritorykey SMALLINT NOT NULL
);

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( countrykey );

ALTER TABLE country ADD CONSTRAINT country_code_un UNIQUE ( code );

ALTER TABLE country ADD CONSTRAINT country_name_un UNIQUE ( name );

CREATE TABLE customer (
    customerkey      INTEGER NOT NULL,
    email            VARCHAR2(50 CHAR) NOT NULL,
    password         VARCHAR2(50 CHAR) NOT NULL,
    firstname        VARCHAR2(50 CHAR) NOT NULL,
    lastname         VARCHAR2(50 CHAR) NOT NULL,
    phonenumber      VARCHAR2(11 CHAR),
    birthday         DATE,
    address          VARCHAR2(80 CHAR) NOT NULL,
    creationdate     DATE NOT NULL,
    modificationdate DATE NOT NULL,
    citykey          INTEGER,
    administratorkey SMALLINT NOT NULL
);

CREATE UNIQUE INDEX customer_uidx ON
    customer (
        customerkey
    ASC,
        email
    ASC );

CREATE INDEX customer_idx ON
    customer (
        lastname
    ASC,
        firstname
    ASC,
        phonenumber
    ASC,
        address
    ASC,
        birthday
    ASC,
        creationdate
    DESC,
        modificationdate
    DESC );

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customerkey );

ALTER TABLE customer ADD CONSTRAINT customer_email_un UNIQUE ( email );

CREATE TABLE deliverymethod (
    deliverymethodkey SMALLINT NOT NULL,
    name              VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE deliverymethod ADD CONSTRAINT deliverymethod_pk PRIMARY KEY ( deliverymethodkey );

ALTER TABLE deliverymethod ADD CONSTRAINT deliverymethod_name_un UNIQUE ( name );

CREATE TABLE employee (
    employeekey   INTEGER NOT NULL,
    firstname     VARCHAR2(50 CHAR) NOT NULL,
    lastname      VARCHAR2(50 CHAR) NOT NULL,
    email         VARCHAR2(50 CHAR) NOT NULL,
    phonenumber   VARCHAR2(11 CHAR) NOT NULL,
    salespointkey INTEGER NOT NULL
);

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employeekey );

ALTER TABLE employee ADD CONSTRAINT employee_email_un UNIQUE ( email );

ALTER TABLE employee ADD CONSTRAINT employee_phonenumber_un UNIQUE ( phonenumber );

CREATE TABLE orderdetail (
    orderdetailkey     INTEGER NOT NULL,
    quantity           NUMBER(3) NOT NULL,
    catalogprice       NUMBER(10, 2) NOT NULL,
    discountamount     NUMBER(10, 2),
    discountpercentage NUMBER(2, 2),
    transactionprice   NUMBER(10, 2) NOT NULL,
    refundkey          INTEGER,
    orderkey           INTEGER NOT NULL
);

CREATE UNIQUE INDEX orderdetail_uidx ON
    orderdetail (
        orderdetailkey
    ASC,
        refundkey
    ASC );

CREATE INDEX orderdetail_idx ON
    orderdetail (
        transactionprice
    ASC,
        catalogprice
    ASC,
        discountamount
    ASC,
        discountpercentage
    ASC,
        quantity
    ASC );

ALTER TABLE orderdetail ADD CONSTRAINT orderdetail_pk PRIMARY KEY ( orderdetailkey,
                                                                    orderkey );

CREATE TABLE orderdetail_product_fk (
    productkey     INTEGER NOT NULL,
    orderdetailkey INTEGER NOT NULL,
    od_oh_orderkey INTEGER NOT NULL
);

ALTER TABLE orderdetail_product_fk
    ADD CONSTRAINT orderdetail_product_fk_pk PRIMARY KEY ( productkey,
                                                           orderdetailkey,
                                                           od_oh_orderkey );

CREATE TABLE orderheader (
    orderkey          INTEGER NOT NULL,
    orderdate         DATE NOT NULL,
    deliverydate      DATE NOT NULL,
    deliverycost      NUMBER(10, 2) NOT NULL,
    deliverymethodkey SMALLINT NOT NULL,
    salespointkey     INTEGER,
    paymentmethodkey  SMALLINT NOT NULL,
    countrykey        SMALLINT NOT NULL,
    customerkey       INTEGER NOT NULL,
    orderstatuskey    SMALLINT NOT NULL
);

CREATE UNIQUE INDEX orderheader_uidx ON
    orderheader (
        orderkey
    ASC );

CREATE INDEX orderheader_idx ON
    orderheader (
        orderdate
    DESC,
        deliverydate
    DESC,
        deliverycost
    ASC );

ALTER TABLE orderheader ADD CONSTRAINT orderheader_pk PRIMARY KEY ( orderkey );

CREATE TABLE orderstatus (
    orderstatuskey SMALLINT NOT NULL,
    name           VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE orderstatus ADD CONSTRAINT orderstatus_pk PRIMARY KEY ( orderstatuskey );

ALTER TABLE orderstatus ADD CONSTRAINT orderstatus_name_un UNIQUE ( name );

CREATE TABLE paymentmethod (
    paymentmethodkey SMALLINT NOT NULL,
    name             VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE paymentmethod ADD CONSTRAINT paymentmethod_pk PRIMARY KEY ( paymentmethodkey );

ALTER TABLE paymentmethod ADD CONSTRAINT paymentmethod_name_un UNIQUE ( name );

CREATE TABLE product (
    productkey            INTEGER NOT NULL,
    code                  VARCHAR2(10 CHAR) NOT NULL,
    name                  VARCHAR2(50 CHAR) NOT NULL,
    salespointkey         INTEGER NOT NULL,
    productsubcategorykey SMALLINT NOT NULL
);

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( productkey );

ALTER TABLE product ADD CONSTRAINT product_code_un UNIQUE ( code );

ALTER TABLE product ADD CONSTRAINT product_name_un UNIQUE ( name );

CREATE TABLE productcategory (
    productcategorykey SMALLINT NOT NULL,
    name               VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE productcategory ADD CONSTRAINT productcategory_pk PRIMARY KEY ( productcategorykey );

ALTER TABLE productcategory ADD CONSTRAINT productcategory_name_un UNIQUE ( name );

CREATE TABLE productsubcategory (
    productsubcategorykey SMALLINT NOT NULL,
    name                  VARCHAR2(50 CHAR) NOT NULL,
    productcategorykey    SMALLINT NOT NULL
);

ALTER TABLE productsubcategory ADD CONSTRAINT productsubcategory_pk PRIMARY KEY ( productsubcategorykey );

ALTER TABLE productsubcategory ADD CONSTRAINT productsubcategory_name_un UNIQUE ( name );

CREATE TABLE question (
    questionkey INTEGER NOT NULL,
    title       VARCHAR2(20 CHAR) NOT NULL,
    body        VARCHAR2(250 CHAR) NOT NULL,
    customerkey INTEGER NOT NULL,
    productkey  INTEGER NOT NULL
);

ALTER TABLE question ADD CONSTRAINT question_pk PRIMARY KEY ( questionkey );

CREATE TABLE refund (
    refundkey    INTEGER NOT NULL,
    refundoption CHAR(1) NOT NULL,
    title        VARCHAR2(50 CHAR) NOT NULL,
    "Date"       DATE NOT NULL
);

ALTER TABLE refund ADD CONSTRAINT refund_pk PRIMARY KEY ( refundkey );

CREATE TABLE salereport (
    salereportkey INTEGER NOT NULL,
    title         VARCHAR2(50) NOT NULL,
    "Date"        DATE NOT NULL,
    salespointkey INTEGER NOT NULL
);

ALTER TABLE salereport ADD CONSTRAINT salereport_pk PRIMARY KEY ( salereportkey );

CREATE TABLE salespoint (
    salespointkey    INTEGER NOT NULL,
    address          VARCHAR2(80 CHAR) NOT NULL,
    contactnumber    VARCHAR2(11 CHAR) NOT NULL,
    modificationdate DATE NOT NULL,
    citykey          INTEGER NOT NULL,
    administratorkey SMALLINT NOT NULL
);

CREATE UNIQUE INDEX salespoint_uidx ON
    salespoint (
        salespointkey
    ASC,
        address
    ASC );

CREATE INDEX salespoint_idx ON
    salespoint (
        contactnumber
    ASC,
        modificationdate
    DESC );

ALTER TABLE salespoint ADD CONSTRAINT salespoint_pk PRIMARY KEY ( salespointkey );

ALTER TABLE salespoint ADD CONSTRAINT salespoint_address_un UNIQUE ( address );

CREATE TABLE salesterritory (
    salesterritorykey SMALLINT NOT NULL,
    name              VARCHAR2(50 CHAR) NOT NULL
);

ALTER TABLE salesterritory ADD CONSTRAINT salesterritory_pk PRIMARY KEY ( salesterritorykey );

ALTER TABLE salesterritory ADD CONSTRAINT salesterritory_name_un UNIQUE ( name );

ALTER TABLE customer
    ADD CONSTRAINT administrator_fk FOREIGN KEY ( administratorkey )
        REFERENCES administrator ( administratorkey );

ALTER TABLE salespoint
    ADD CONSTRAINT administrator_fkv1 FOREIGN KEY ( administratorkey )
        REFERENCES administrator ( administratorkey );

ALTER TABLE customer
    ADD CONSTRAINT city_fk FOREIGN KEY ( citykey )
        REFERENCES city ( citykey );

ALTER TABLE salespoint
    ADD CONSTRAINT city_fkv1 FOREIGN KEY ( citykey )
        REFERENCES city ( citykey );

ALTER TABLE city
    ADD CONSTRAINT country_fk FOREIGN KEY ( countrykey )
        REFERENCES country ( countrykey );

ALTER TABLE orderheader
    ADD CONSTRAINT country_fkv1 FOREIGN KEY ( countrykey )
        REFERENCES country ( countrykey );

ALTER TABLE question
    ADD CONSTRAINT customer_fk FOREIGN KEY ( customerkey )
        REFERENCES customer ( customerkey );

ALTER TABLE orderheader
    ADD CONSTRAINT customer_fkv1 FOREIGN KEY ( customerkey )
        REFERENCES customer ( customerkey );

ALTER TABLE orderheader
    ADD CONSTRAINT deliverymethod_fk FOREIGN KEY ( deliverymethodkey )
        REFERENCES deliverymethod ( deliverymethodkey );

ALTER TABLE answer
    ADD CONSTRAINT employee_fk FOREIGN KEY ( employeekey )
        REFERENCES employee ( employeekey );

ALTER TABLE orderdetail_product_fk
    ADD CONSTRAINT od_product_fk_odl_fk FOREIGN KEY ( orderdetailkey,
                                                      od_oh_orderkey )
        REFERENCES orderdetail ( orderdetailkey,
                                 orderkey );

ALTER TABLE orderdetail_product_fk
    ADD CONSTRAINT od_product_fk_product_fk FOREIGN KEY ( productkey )
        REFERENCES product ( productkey );

ALTER TABLE orderdetail
    ADD CONSTRAINT orderheader_fk FOREIGN KEY ( orderkey )
        REFERENCES orderheader ( orderkey );

ALTER TABLE orderheader
    ADD CONSTRAINT orderstatus_fk FOREIGN KEY ( orderstatuskey )
        REFERENCES orderstatus ( orderstatuskey );

ALTER TABLE orderheader
    ADD CONSTRAINT paymentmethod_fk FOREIGN KEY ( paymentmethodkey )
        REFERENCES paymentmethod ( paymentmethodkey );

ALTER TABLE question
    ADD CONSTRAINT product_fk FOREIGN KEY ( productkey )
        REFERENCES product ( productkey );

ALTER TABLE productsubcategory
    ADD CONSTRAINT productcategory_fk FOREIGN KEY ( productcategorykey )
        REFERENCES productcategory ( productcategorykey );

ALTER TABLE product
    ADD CONSTRAINT productsubcategory_fk FOREIGN KEY ( productsubcategorykey )
        REFERENCES productsubcategory ( productsubcategorykey );

ALTER TABLE answer
    ADD CONSTRAINT question_fk FOREIGN KEY ( questionkey )
        REFERENCES question ( questionkey );

ALTER TABLE orderdetail
    ADD CONSTRAINT refund_fk FOREIGN KEY ( refundkey )
        REFERENCES refund ( refundkey );

ALTER TABLE answer
    ADD CONSTRAINT salespoint_fk FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE product
    ADD CONSTRAINT salespoint_fkv1 FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE employee
    ADD CONSTRAINT salespoint_fkv2 FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE salereport
    ADD CONSTRAINT salespoint_fkv3 FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE orderheader
    ADD CONSTRAINT salespoint_fkv4 FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE country
    ADD CONSTRAINT salesterritory_fk FOREIGN KEY ( salesterritorykey )
        REFERENCES salesterritory ( salesterritorykey );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            20
-- CREATE INDEX                             8
-- ALTER TABLE                             63
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
