-- Generated by Oracle SQL Developer Data Modeler 23.1.0.087.0806
--   at:        2024-01-12 22:29:40 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE administrator (
    administratorkey SMALLINT NOT NULL,
    name             VARCHAR2(50 CHAR) NOT NULL,
    phonenumber      VARCHAR2(11 CHAR) NOT NULL
);

CREATE UNIQUE INDEX administrator_uidx ON
    administrator (
        administratorkey
    ASC );

CREATE INDEX administrator_idx ON
    administrator (
        name
    ASC,
        phonenumber
    ASC );

ALTER TABLE administrator ADD CONSTRAINT administrator_pk PRIMARY KEY ( administratorkey );

ALTER TABLE administrator ADD CONSTRAINT administrator_name_un UNIQUE ( name );

ALTER TABLE administrator ADD CONSTRAINT administrator_phonenumber_un UNIQUE ( phonenumber );

CREATE TABLE answear (
    answearkey    INTEGER NOT NULL,
    body          VARCHAR2(250 CHAR) NOT NULL,
    questionkey   INTEGER NOT NULL,
    salespointkey INTEGER,
    employeekey   INTEGER NOT NULL
);

CREATE UNIQUE INDEX answear_uidx ON
    answear (
        answearkey
    ASC );

ALTER TABLE answear ADD CONSTRAINT answear_pk PRIMARY KEY ( answearkey );

CREATE TABLE city (
    citykey    INTEGER NOT NULL,
    name       VARCHAR2(50 CHAR) NOT NULL,
    postalcode VARCHAR2(50 CHAR) NOT NULL,
    countrykey SMALLINT NOT NULL
);

CREATE UNIQUE INDEX city_uidx ON
    city (
        citykey
    ASC );

CREATE INDEX city_idx ON
    city (
        postalcode
    ASC,
        name
    ASC );

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( citykey );

ALTER TABLE city ADD CONSTRAINT city_postalcode_un UNIQUE ( postalcode );

CREATE TABLE country (
    countrykey        SMALLINT NOT NULL,
    name              VARCHAR2(50 CHAR) NOT NULL,
    code              VARCHAR2(50 CHAR) NOT NULL,
    salesterritorykey SMALLINT NOT NULL
);

CREATE UNIQUE INDEX country_uidx ON
    country (
        countrykey
    ASC );

CREATE INDEX country_idx ON
    country (
        code
    ASC,
        name
    ASC );

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( countrykey );

ALTER TABLE country ADD CONSTRAINT country_code_un UNIQUE ( code );

ALTER TABLE country ADD CONSTRAINT country_name_un UNIQUE ( name );

CREATE TABLE customer (
    customerkey      INTEGER NOT NULL,
    email            VARCHAR2(50 CHAR) NOT NULL,
    password         VARCHAR2(50 CHAR) NOT NULL,
    firstname        VARCHAR2(50 CHAR) NOT NULL,
    lastname         VARCHAR2(50 CHAR) NOT NULL,
    phonenumber      VARCHAR2(11 CHAR),
    birthday         DATE,
    address          VARCHAR2(80 CHAR) NOT NULL,
    creationdate     DATE NOT NULL,
    modificationdate DATE NOT NULL,
    citykey          INTEGER,
    administratorkey SMALLINT NOT NULL
);

CREATE UNIQUE INDEX customer_uidx ON
    customer (
        customerkey
    ASC );

CREATE INDEX customer_idx ON
    customer (
        email
    ASC,
        phonenumber
    ASC,
        lastname
    ASC,
        firstname
    ASC,
        address
    ASC,
        birthday
    ASC,
        creationdate
    DESC,
        modificationdate
    DESC );

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( customerkey );

ALTER TABLE customer ADD CONSTRAINT customer_email_un UNIQUE ( email );

CREATE TABLE deliverymethod (
    deliverymethodkey SMALLINT NOT NULL,
    name              VARCHAR2(50 CHAR) NOT NULL
);

CREATE UNIQUE INDEX deliverymethod_uidx ON
    deliverymethod (
        deliverymethodkey
    ASC );

CREATE INDEX deliverymethod_idx ON
    deliverymethod (
        name
    ASC );

ALTER TABLE deliverymethod ADD CONSTRAINT deliverymethod_pk PRIMARY KEY ( deliverymethodkey );

ALTER TABLE deliverymethod ADD CONSTRAINT deliverymethod_name_un UNIQUE ( name );

CREATE TABLE employee (
    employeekey   INTEGER NOT NULL,
    firstname     VARCHAR2(50 CHAR) NOT NULL,
    lastname      VARCHAR2(50 CHAR) NOT NULL,
    email         VARCHAR2(50 CHAR) NOT NULL,
    phonenumber   VARCHAR2(11 CHAR) NOT NULL,
    salespointkey INTEGER NOT NULL
);

CREATE UNIQUE INDEX employee_uidx ON
    employee (
        employeekey
    ASC );

CREATE INDEX employee_idx ON
    employee (
        phonenumber
    ASC,
        email
    ASC,
        lastname
    ASC,
        firstname
    ASC );

ALTER TABLE employee ADD CONSTRAINT employee_pk PRIMARY KEY ( employeekey );

ALTER TABLE employee ADD CONSTRAINT employee_email_un UNIQUE ( email );

ALTER TABLE employee ADD CONSTRAINT employee_phonenumber_un UNIQUE ( phonenumber );

CREATE TABLE orderdetail (
    orderdetailkey     INTEGER NOT NULL,
    quantity           NUMBER(3) NOT NULL,
    catalogprice       NUMBER(10, 2) NOT NULL,
    discountamount     NUMBER(10, 2),
    discountpercentage NUMBER(2, 2),
    transactionprice   NUMBER(10, 2) NOT NULL,
    refundkey          INTEGER,
    orderkey           INTEGER NOT NULL
);

CREATE UNIQUE INDEX orderdetail_uidx ON
    orderdetail (
        orderdetailkey
    ASC );

CREATE INDEX orderdetail_idx ON
    orderdetail (
        transactionprice
    ASC,
        catalogprice
    ASC,
        discountamount
    ASC,
        discountpercentage
    ASC );

ALTER TABLE orderdetail ADD CONSTRAINT orderdetail_pk PRIMARY KEY ( orderdetailkey,
                                                                    orderkey );

CREATE TABLE orderheader (
    orderkey          INTEGER NOT NULL,
    orderdate         DATE NOT NULL,
    deliverydate      DATE NOT NULL,
    deliverycost      NUMBER(10, 2) NOT NULL,
    deliverymethodkey SMALLINT NOT NULL,
    salespointkey     INTEGER,
    paymentmethodkey  SMALLINT NOT NULL,
    countrykey        SMALLINT NOT NULL,
    customerkey       INTEGER NOT NULL,
    orderstatuskey    SMALLINT NOT NULL
);

CREATE UNIQUE INDEX orderheader_uidx ON
    orderheader (
        orderkey
    ASC );

CREATE INDEX orderheader_idx ON
    orderheader (
        orderdate
    DESC,
        deliverydate
    DESC,
        deliverycost
    ASC );

ALTER TABLE orderheader ADD CONSTRAINT orderheader_pk PRIMARY KEY ( orderkey );

CREATE TABLE orderstatus (
    orderstatuskey SMALLINT NOT NULL,
    name           VARCHAR2(50 CHAR) NOT NULL
);

CREATE UNIQUE INDEX orderstatus_uidx ON
    orderstatus (
        orderstatuskey
    ASC );

CREATE INDEX orderstatus_idx ON
    orderstatus (
        name
    ASC );

ALTER TABLE orderstatus ADD CONSTRAINT orderstatus_pk PRIMARY KEY ( orderstatuskey );

ALTER TABLE orderstatus ADD CONSTRAINT orderstatus_name_un UNIQUE ( name );

CREATE TABLE paymentmethod (
    paymentmethodkey SMALLINT NOT NULL,
    name             VARCHAR2(50 CHAR) NOT NULL
);

CREATE UNIQUE INDEX paymentmethod_uidx ON
    paymentmethod (
        paymentmethodkey
    ASC );

CREATE INDEX paymentmethod_idx ON
    paymentmethod (
        name
    ASC );

ALTER TABLE paymentmethod ADD CONSTRAINT paymentmethod_pk PRIMARY KEY ( paymentmethodkey );

ALTER TABLE paymentmethod ADD CONSTRAINT paymentmethod_name_un UNIQUE ( name );

CREATE TABLE product (
    productkey            INTEGER NOT NULL,
    code                  VARCHAR2(10 CHAR) NOT NULL,
    name                  VARCHAR2(50 CHAR) NOT NULL,
    salespointkey         INTEGER NOT NULL,
    productsubcategorykey SMALLINT NOT NULL
);

CREATE UNIQUE INDEX product_uidx ON
    product (
        productkey
    ASC );

CREATE INDEX product_idx ON
    product (
        code
    ASC,
        name
    ASC );

ALTER TABLE product ADD CONSTRAINT product_pk PRIMARY KEY ( productkey );

ALTER TABLE product ADD CONSTRAINT product_code_un UNIQUE ( code );

ALTER TABLE product ADD CONSTRAINT product_name_un UNIQUE ( name );

CREATE TABLE productcategory (
    productcategorykey SMALLINT NOT NULL,
    name               VARCHAR2(50 CHAR) NOT NULL
);

CREATE UNIQUE INDEX productcategory_uidx ON
    productcategory (
        productcategorykey
    ASC );

CREATE INDEX productcategory_idx ON
    productcategory (
        name
    ASC );

ALTER TABLE productcategory ADD CONSTRAINT productcategory_pk PRIMARY KEY ( productcategorykey );

ALTER TABLE productcategory ADD CONSTRAINT productcategory_name_un UNIQUE ( name );

CREATE TABLE productlist (
    product_productkey INTEGER NOT NULL,
    od_orderdetailkey  INTEGER NOT NULL,
    od_oh_orderkey     INTEGER NOT NULL
);

CREATE UNIQUE INDEX productlist_uidx ON
    productlist (
        product_productkey
    ASC );

ALTER TABLE productlist
    ADD CONSTRAINT orderdetail_product_fk_pk PRIMARY KEY ( product_productkey,
                                                           od_orderdetailkey,
                                                           od_oh_orderkey );

CREATE TABLE productsubcategory (
    productsubcategorykey SMALLINT NOT NULL,
    name                  VARCHAR2(50 CHAR) NOT NULL,
    productcategorykey    SMALLINT NOT NULL
);

CREATE UNIQUE INDEX productsubcategory_uidx ON
    productsubcategory (
        productsubcategorykey
    ASC );

CREATE INDEX productsubcategory_idx ON
    productsubcategory (
        name
    ASC );

ALTER TABLE productsubcategory ADD CONSTRAINT productsubcategory_pk PRIMARY KEY ( productsubcategorykey );

ALTER TABLE productsubcategory ADD CONSTRAINT productsubcategory_name_un UNIQUE ( name );

CREATE TABLE question (
    questionkey INTEGER NOT NULL,
    title       VARCHAR2(20 CHAR) NOT NULL,
    body        VARCHAR2(250 CHAR) NOT NULL,
    customerkey INTEGER NOT NULL,
    productkey  INTEGER NOT NULL
);

CREATE UNIQUE INDEX question_uidx ON
    question (
        questionkey
    ASC );

CREATE INDEX question_idx ON
    question (
        title
    ASC );

ALTER TABLE question ADD CONSTRAINT question_pk PRIMARY KEY ( questionkey );

CREATE TABLE refund (
    refundkey    INTEGER NOT NULL,
    refundoption CHAR(1) NOT NULL,
    title        VARCHAR2(50 CHAR) NOT NULL,
    "Date"       DATE NOT NULL
);

CREATE UNIQUE INDEX refund_uidx ON
    refund (
        refundkey
    ASC );

CREATE INDEX refund_idx ON
    refund (
        "Date"
    DESC,
        title
    ASC,
        refundoption
    ASC );

ALTER TABLE refund ADD CONSTRAINT refund_pk PRIMARY KEY ( refundkey );

CREATE TABLE salereport (
    salereportkey INTEGER NOT NULL,
    title         VARCHAR2(50) NOT NULL,
    "Date"        DATE NOT NULL,
    salespointkey INTEGER NOT NULL
);

CREATE UNIQUE INDEX salereport_uidx ON
    salereport (
        salereportkey
    ASC );

CREATE INDEX salereport_idx ON
    salereport (
        "Date"
    DESC,
        title
    ASC );

ALTER TABLE salereport ADD CONSTRAINT salereport_pk PRIMARY KEY ( salereportkey );

CREATE TABLE salespoint (
    salespointkey    INTEGER NOT NULL,
    address          VARCHAR2(80 CHAR) NOT NULL,
    contactnumber    VARCHAR2(11 CHAR) NOT NULL,
    modificationdate DATE NOT NULL,
    citykey          INTEGER NOT NULL,
    administratorkey SMALLINT NOT NULL
);

CREATE UNIQUE INDEX salespoint_uidx ON
    salespoint (
        salespointkey
    ASC );

CREATE INDEX salespoint_idx ON
    salespoint (
        address
    ASC,
        contactnumber
    ASC,
        modificationdate
    DESC );

ALTER TABLE salespoint ADD CONSTRAINT salespoint_pk PRIMARY KEY ( salespointkey );

ALTER TABLE salespoint ADD CONSTRAINT salespoint_address_un UNIQUE ( address );

CREATE TABLE salesterritory (
    salesterritorykey SMALLINT NOT NULL,
    name              VARCHAR2(50 CHAR) NOT NULL
);

CREATE UNIQUE INDEX salesterritory_uidx ON
    salesterritory (
        salesterritorykey
    ASC );

CREATE INDEX salesterritory_idx ON
    salesterritory (
        name
    ASC );

ALTER TABLE salesterritory ADD CONSTRAINT salesterritory_pk PRIMARY KEY ( salesterritorykey );

ALTER TABLE salesterritory ADD CONSTRAINT salesterritory_name_un UNIQUE ( name );

ALTER TABLE customer
    ADD CONSTRAINT administrator_fk FOREIGN KEY ( administratorkey )
        REFERENCES administrator ( administratorkey );

ALTER TABLE salespoint
    ADD CONSTRAINT administrator_fkv1 FOREIGN KEY ( administratorkey )
        REFERENCES administrator ( administratorkey );

ALTER TABLE customer
    ADD CONSTRAINT city_fk FOREIGN KEY ( citykey )
        REFERENCES city ( citykey );

ALTER TABLE salespoint
    ADD CONSTRAINT city_fkv1 FOREIGN KEY ( citykey )
        REFERENCES city ( citykey );

ALTER TABLE city
    ADD CONSTRAINT country_fk FOREIGN KEY ( countrykey )
        REFERENCES country ( countrykey );

ALTER TABLE orderheader
    ADD CONSTRAINT country_fkv1 FOREIGN KEY ( countrykey )
        REFERENCES country ( countrykey );

ALTER TABLE orderheader
    ADD CONSTRAINT customer_fk FOREIGN KEY ( customerkey )
        REFERENCES customer ( customerkey );

ALTER TABLE question
    ADD CONSTRAINT customer_fkv1 FOREIGN KEY ( customerkey )
        REFERENCES customer ( customerkey );

ALTER TABLE orderheader
    ADD CONSTRAINT deliverymethod_fk FOREIGN KEY ( deliverymethodkey )
        REFERENCES deliverymethod ( deliverymethodkey );

ALTER TABLE answear
    ADD CONSTRAINT employee_fk FOREIGN KEY ( employeekey )
        REFERENCES employee ( employeekey );

ALTER TABLE productlist
    ADD CONSTRAINT orderdetail_fk FOREIGN KEY ( od_orderdetailkey,
                                                od_oh_orderkey )
        REFERENCES orderdetail ( orderdetailkey,
                                 orderkey );

ALTER TABLE orderdetail
    ADD CONSTRAINT orderheader_fk FOREIGN KEY ( orderkey )
        REFERENCES orderheader ( orderkey );

ALTER TABLE orderheader
    ADD CONSTRAINT orderstatus_fk FOREIGN KEY ( orderstatuskey )
        REFERENCES orderstatus ( orderstatuskey );

ALTER TABLE orderheader
    ADD CONSTRAINT paymentmethod_fk FOREIGN KEY ( paymentmethodkey )
        REFERENCES paymentmethod ( paymentmethodkey );

ALTER TABLE question
    ADD CONSTRAINT product_fk FOREIGN KEY ( productkey )
        REFERENCES product ( productkey );

ALTER TABLE productlist
    ADD CONSTRAINT product_fkv1 FOREIGN KEY ( product_productkey )
        REFERENCES product ( productkey );

ALTER TABLE productsubcategory
    ADD CONSTRAINT productcategory_fk FOREIGN KEY ( productcategorykey )
        REFERENCES productcategory ( productcategorykey );

ALTER TABLE product
    ADD CONSTRAINT productsubcategory_fk FOREIGN KEY ( productsubcategorykey )
        REFERENCES productsubcategory ( productsubcategorykey );

ALTER TABLE answear
    ADD CONSTRAINT question_fk FOREIGN KEY ( questionkey )
        REFERENCES question ( questionkey );

ALTER TABLE orderdetail
    ADD CONSTRAINT refund_fk FOREIGN KEY ( refundkey )
        REFERENCES refund ( refundkey );

ALTER TABLE orderheader
    ADD CONSTRAINT salespoint_fk FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE answear
    ADD CONSTRAINT salespoint_fkv1 FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE product
    ADD CONSTRAINT salespoint_fkv2 FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE employee
    ADD CONSTRAINT salespoint_fkv3 FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE salereport
    ADD CONSTRAINT salespoint_fkv4 FOREIGN KEY ( salespointkey )
        REFERENCES salespoint ( salespointkey );

ALTER TABLE country
    ADD CONSTRAINT salesterritory_fk FOREIGN KEY ( salesterritorykey )
        REFERENCES salesterritory ( salesterritorykey );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            20
-- CREATE INDEX                            38
-- ALTER TABLE                             63
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
